const backendDomain="http://localhost:8080";

const summaryAPI={
    signup:{
        url:`${backendDomain}/signup`,
        method:"post",
    },
    login:{
        url:`${backendDomain}/login`,
        method:"post",
    },
    userDetails:{
        url:`${backendDomain}/user-details`,
        method:"get",
    },
    logout:{
        url:`${backendDomain}/logout`,
        method:"get",
    },
    allUsers:{
        url:`${backendDomain}/all-users`,
        method:"get",
    },
    updateUser:{
        url:`${backendDomain}/updateUser`,
        method:"post",
    },
    addProduct:{
        url:`${backendDomain}/add-product`,
        method:"post",
    },
    allProduct:{
        url:`${backendDomain}/all-product`,
        method:"get",
    },
    editProduct:{
        url:`${backendDomain}/editProduct`,
        method:"post",
    },
    categoryProduct:{
        url:`${backendDomain}/category-product`,
        method:"get",
    },
    categoryWiseProduct:{
        url:`${backendDomain}/category-wise-product`,
        method:"post",
    },
    productDetails:{
        url:`${backendDomain}/product-details`,
        method:"post",
    },
    addToCart:{
        url:`${backendDomain}/addtocart`,
        method:"post",
    },
    cartCount:{
        url:`${backendDomain}/cartCount`,
        method:"get",
    },
    dsiplayCart:{
        url:`${backendDomain}/viewcart`,
        method:"get",
    },
    updateQuantity:{
        url:`${backendDomain}/updateQuantity`,
        method:"post",
    }, 
    deleteCartProduct:{
        url:`${backendDomain}/deleteCartProduct`,
        method:"post",
    }, 
    searchBar:{
        url:`${backendDomain}/search`,
        method:"get",
    }, 
    filterBy:{
        url:`${backendDomain}/filtered-products`,
        method:"post",
    }, 
}

export default summaryAPI;

